# -*- coding: utf-8 -*-
"""mini_gpt.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yXHq7aYW_JFtbEi2AlQqG7DLWJ3-B4i

Attention
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

class SelfAttention(nn.Module):
  def __init__(self, d_model, num_heads):
    super().__init__()

    self.num_heads = num_heads
    self.d_k = d_model // num_heads

    self.W_q = nn.Linear(d_model, d_model)
    self.W_k = nn.Linear(d_model, d_model)
    self.W_v = nn.Linear(d_model, d_model)

    self.W_o = nn.Linear(d_model, d_model)

  def forward(self, x):
    batch, seq_len, d_model = x.shape

    Q = self.W_q(x)
    K = self.W_k(x)
    V = self.W_v(x)

    scores = Q @ K.transpose(-2, -1)
    scores = scores / math.sqrt(self.d_k)

    mask = torch.tril(torch.ones(seq_len, seq_len)).to(x.device)
    scores = scores.masked_fill(mask == 0, float('-inf'))

    weights = F.softmax(scores, dim=-1)
    output = weights @ V
    return self.W_o(output)

d_model = 8
num_heads = 2
seq_len = 5
batch = 1

x = torch.randn(batch, seq_len, d_model)
attn = SelfAttention(d_model, num_heads)
out = attn(x)

print("Input Shape", x.shape)
print("Output Shape", out.shape)

"""Feed-Forward Module"""

class FeedForward(nn.Module):
  def __init__(self, d_model, d_ff):
      super().__init__()

      self.net = nn.Sequential(
          nn.Linear(d_model, d_ff),
          nn.ReLU(),
          nn.Linear(d_ff, d_model)
      )

  def forward(self, x):
      return self.net(x)

ff = FeedForward(d_model=8, d_ff=32)
out = ff(x)

print("FFN Input shape:", x.shape)
print("FFN Output shape:", out.shape)

"""Trasnformer block"""

class TrasnformerBlock(nn.Module): # Corrected from nn.module
  def __init__(self, d_model, num_heads, d_ff):
      super().__init__()

      self.attention = SelfAttention(d_model, num_heads)
      self.ff = FeedForward(d_model, d_ff)

      self.norm1 = nn.LayerNorm(d_model)
      self.norm2 = nn.LayerNorm(d_model)

  def forward(self, x):
      x = self.norm1(x + self.attention(x))
      x = self.norm2(x + self.ff(x))

      return x

block = TrasnformerBlock(d_model=8, num_heads=2, d_ff=32)

x = torch.randn(1, 5, 8)
out = block(x)

print("Block input shape:", x.shape)
print("Block output shape:", out.shape)

"""Stack Multiple Blocks - GPT"""

class MiniGPT(nn.Module): # Corrected nn.module to nn.Module
  def __init__(self, vocab_size, d_model, num_heads, d_ff, num_layers, max_seq_len):
      super().__init__()

      self.token_emb = nn.Embedding(vocab_size, d_model)
      self.pos_emb = nn.Embedding(max_seq_len, d_model)

      self.blocks = nn.ModuleList([
          TrasnformerBlock(d_model, num_heads, d_ff)
          for _ in range(num_layers)
      ])

      self.head = nn.Linear(d_model, vocab_size)

  def forward(self, token_ids):
      batch, seq_len = token_ids.shape

      positions = torch.arange(seq_len).unsqueeze(0)
      x = self.token_emb(token_ids) + self.pos_emb(positions)

      for block in self.blocks:
          x = block(x)

      logits = self.head(x)
      return logits


model = MiniGPT(
    vocab_size=100,
    d_model=8,
    num_heads=2,
    d_ff=32,
    num_layers=2,
    max_seq_len=50
)

token_ids = torch.randint(0, 100, (1, 5)) # Corrected torch.randit to torch.randint
logits = model(token_ids)

print("Token IDs shape:", token_ids.shape)
print("Logits shape:", logits.shape)

"""Greedy Generation"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

def generate_greedy(model, imput_ids, max_new_tokens=10):
    model.eval()

    current_ids = input_ids.clone()

    with torch.no_grad():
        for step in range(max_new_tokens):

            logits = model(current_ids)
            next_logits = logits[:, -1, :]
            next_token = torch.argmax(next_logits, dim=-1, keepdim=True)
            current_ids = torch.cat([current_ids, next_token], dim=1)

            print(f"Step {step+1}: generated token {next_token.item()}, "
                  f"sequence lenght = {current_ids.shape[1]}")
    return current_ids

#BuildModel

model = MiniGPT(
    vocab_size=100,
    d_model=8,
    num_heads=2,
    d_ff=32,
    num_layers=2,
    max_seq_len=50
)

input_ids = torch.tensor([[4, 17, 83]])
print("Input IDs:", input_ids)
print("Input shape:", input_ids.shape)
print()

output_ids = generate_greedy(model, input_ids, max_new_tokens=5)

print()
print("Final sequence:", output_ids)
print("Final shape:", output_ids.shape)

"""Temperature Generation"""

def generate_temperature(model, input_ids, max_new_tokens=10, temperature=1.0):

    model.eval()
    current_ids = input_ids.clone()

    with torch.no_grad():
        for step in range(max_new_tokens):

          logits = model(current_ids)
          next_logits = logits[:, -1, :]
          scaled_logits = next_logits / temperature
          probs = F.softmax(scaled_logits, dim=-1)
          next_token = torch.multinomial(probs, num_samples=1) # Corrected 'multinominal' to 'multinomial'
          current_ids = torch.cat([current_ids, next_token], dim=1)

    return current_ids

input_ids = torch.tensor([[4, 17, 83]])

print("=== Temperature 0.5 (more focused) ===")
out = generate_temperature(model, input_ids, max_new_tokens=5, temperature=0.5)
print("Generated:", out[0].tolist())

print()
print("=== Temperature 1.0 (normal) ===")
out = generate_temperature(model, input_ids, max_new_tokens=5, temperature=1.0)
print("Generated:", out[0].tolist())

print()
print("=== Temperature 2.0 (more random) ===")
out = generate_temperature(model, input_ids, max_new_tokens=5, temperature=2.0)
print("Generated:", out[0].tolist())

"""Generation with stop token"""

def generate_with_stop(model, input_ids, max_new_tokens=20,
                        temperature=1.0, eos_token_id=0):
    """
    eos_token_id → end of sequence token
                   generation stops when this token is produced
    """

    model.eval()
    current_ids = input_ids.clone()

    with torch.no_grad():
        for step in range(max_new_tokens):

            # Forward pass
            logits = model(current_ids)
            next_logits = logits[:, -1, :]

            # Temperature + sample
            probs = F.softmax(next_logits / temperature, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)

            # Append
            current_ids = torch.cat([current_ids, next_token], dim=1)

            print(f"Step {step+1}: token = {next_token.item()}")

            # Stop if end token generated
            if next_token.item() == eos_token_id:
                print("→ EOS token reached. Stopping.")
                break

    return current_ids


# Test
input_ids = torch.tensor([[4, 17, 83]])
output = generate_with_stop(model, input_ids,
                             max_new_tokens=20,
                             temperature=1.0,
                             eos_token_id=0)

print()
print("Final sequence:", output[0].tolist())
print("Total length:", output.shape[1])